
using System.Collections.Generic;

namespace Miljokaz.Models
{
    public class ColorModel
    {
        public string Name { get; set; }
        public string HexCode { get; set; }
        public string Status { get; set; }
    }

    public static class Colors
    {
        public static List<ColorModel> ColorList { get; private set; }

        static Colors()
        {
            ColorList = new List<ColorModel>
        {
            new ColorModel { Name = "aliceblue", HexCode = "#F0F8FF", Status = "none" },
            new ColorModel { Name = "antiquewhite", HexCode = "#FAEBD7", Status = "none" },
            new ColorModel { Name = "aqua", HexCode = "#00FFFF", Status = "none" },
            new ColorModel { Name = "aquamarine", HexCode = "#7FFFD4", Status = "none" },
            new ColorModel { Name = "azure", HexCode = "#F0FFFF", Status = "none" },
            new ColorModel { Name = "beige", HexCode = "#F5F5DC", Status = "none" },
            new ColorModel { Name = "bisque", HexCode = "#FFE4C4", Status = "none" },
            new ColorModel { Name = "black", HexCode = "#000000", Status = "none" },
            new ColorModel { Name = "blanchedalmond", HexCode = "#FFEBCD", Status = "none" },
            new ColorModel { Name = "blue", HexCode = "#0000FF", Status = "none" },
            new ColorModel { Name = "blueviolet", HexCode = "#8A2BE2", Status = "none" },
            new ColorModel { Name = "brown", HexCode = "#A52A2A", Status = "none" },
            new ColorModel { Name = "burlywood", HexCode = "#DEB887", Status = "none" },
            new ColorModel { Name = "cadetblue", HexCode = "#5F9EA0", Status = "none" },
            new ColorModel { Name = "chartreuse", HexCode = "#7FFF00", Status = "none" },
            new ColorModel { Name = "chocolate", HexCode = "#D2691E", Status = "none" },
            new ColorModel { Name = "coral", HexCode = "#FF7F50", Status = "none" },
            new ColorModel { Name = "cornflowerblue", HexCode = "#6495ED", Status = "none" },
            new ColorModel { Name = "cornsilk", HexCode = "#FFF8DC", Status = "none" },
            new ColorModel { Name = "crimson", HexCode = "#DC143C", Status = "none" },
            new ColorModel { Name = "cyan", HexCode = "#00FFFF", Status = "none" },
            new ColorModel { Name = "darkblue", HexCode = "#00008B", Status = "none" },
            new ColorModel { Name = "darkcyan", HexCode = "#008B8B", Status = "none" },
            new ColorModel { Name = "darkgoldenrod", HexCode = "#B8860B", Status = "none" },
            new ColorModel { Name = "darkgray", HexCode = "#A9A9A9", Status = "none" },
            new ColorModel { Name = "darkgreen", HexCode = "#006400", Status = "none" },
            new ColorModel { Name = "darkkhaki", HexCode = "#BDB76B", Status = "none" },
            new ColorModel { Name = "darkmagenta", HexCode = "#8B008B", Status = "none" },
            new ColorModel { Name = "darkolivegreen", HexCode = "#556B2F", Status = "none" },
            new ColorModel { Name = "darkorange", HexCode = "#FF8C00", Status = "none" },
            new ColorModel { Name = "darkorchid", HexCode = "#9932CC", Status = "none" },
            new ColorModel { Name = "darkred", HexCode = "#8B0000", Status = "none" },
            new ColorModel { Name = "darksalmon", HexCode = "#E9967A", Status = "none" },
            new ColorModel { Name = "darkseagreen", HexCode = "#8FBC8B", Status = "none" },
            new ColorModel { Name = "darkslateblue", HexCode = "#483D8B", Status = "none" },
            new ColorModel { Name = "darkslategray", HexCode = "#2F4F4F", Status = "none" },
            new ColorModel { Name = "darkturquoise", HexCode = "#00CED1", Status = "none" },
            new ColorModel { Name = "darkviolet", HexCode = "#9400D3", Status = "none" },
            new ColorModel { Name = "deeppink", HexCode = "#FF1493", Status = "none" },
            new ColorModel { Name = "deepskyblue", HexCode = "#00BFFF", Status = "none" },
            new ColorModel { Name = "dimgray", HexCode = "#696969", Status = "none" },
            new ColorModel { Name = "dodgerblue", HexCode = "#1E90FF", Status = "none" },
            new ColorModel { Name = "firebrick", HexCode = "#B22222", Status = "none" },
            new ColorModel { Name = "floralwhite", HexCode = "#FFFAF0", Status = "none" },
            new ColorModel { Name = "forestgreen", HexCode = "#228B22", Status = "none" },
            new ColorModel { Name = "fuchsia", HexCode = "#FF00FF", Status = "none" },
            new ColorModel { Name = "gainsboro", HexCode = "#DCDCDC", Status = "none" },
            new ColorModel { Name = "ghostwhite", HexCode = "#F8F8FF", Status = "none" },
            new ColorModel { Name = "gold", HexCode = "#FFD700", Status = "none" },
            new ColorModel { Name = "goldenrod", HexCode = "#DAA520", Status = "none" },
            new ColorModel { Name = "gray", HexCode = "#808080", Status = "none" },
            new ColorModel { Name = "green", HexCode = "#008000", Status = "none" },
            new ColorModel { Name = "greenyellow", HexCode = "#ADFF2F", Status = "none" },
            new ColorModel { Name = "honeydew", HexCode = "#F0FFF0", Status = "none" },
            new ColorModel { Name = "hotpink", HexCode = "#FF69B4", Status = "none" },
            new ColorModel { Name = "indianred", HexCode = "#CD5C5C", Status = "none" },
            new ColorModel { Name = "indigo", HexCode = "#4B0082", Status = "none" },
            new ColorModel { Name = "ivory", HexCode = "#FFFFF0", Status = "none" },
            new ColorModel { Name = "khaki", HexCode = "#F0E68C", Status = "none" },
            new ColorModel { Name = "lavender", HexCode = "#E6E6FA", Status = "none" },
            new ColorModel { Name = "lavenderblush", HexCode = "#FFF0F5", Status = "none" },
            new ColorModel { Name = "lawngreen", HexCode = "#7CFC00", Status = "none" },
            new ColorModel { Name = "lemonchiffon", HexCode = "#FFFACD", Status = "none" },
            new ColorModel { Name = "lightblue", HexCode = "#ADD8E6", Status = "none" },
            new ColorModel { Name = "lightcoral", HexCode = "#F08080", Status = "none" },
            new ColorModel { Name = "lightcyan", HexCode = "#E0FFFF", Status = "none" },
            new ColorModel { Name = "lightgoldenrodyellow", HexCode = "#FAFAD2", Status = "none" },
            new ColorModel { Name = "lightgray", HexCode = "#D3D3D3", Status = "none" },
            new ColorModel { Name = "lightgreen", HexCode = "#90EE90", Status = "none" },
            new ColorModel { Name = "lightpink", HexCode = "#FFB6C1", Status = "none" },
            new ColorModel { Name = "lightsalmon", HexCode = "#FFA07A", Status = "none" },
            new ColorModel { Name = "lightseagreen", HexCode = "#20B2AA", Status = "none" },
            new ColorModel { Name = "lightskyblue", HexCode = "#87CEFA", Status = "none" },
            new ColorModel { Name = "lightslategray", HexCode = "#778899", Status = "none" },
            new ColorModel { Name = "lightsteelblue", HexCode = "#B0C4DE", Status = "none" },
            new ColorModel { Name = "lightyellow", HexCode = "#FFFFE0", Status = "none" },
            new ColorModel { Name = "lime", HexCode = "#00FF00", Status = "none" },
            new ColorModel { Name = "limegreen", HexCode = "#32CD32", Status = "none" },
            new ColorModel { Name = "linen", HexCode = "#FAF0E6", Status = "none" },
            new ColorModel { Name = "magenta", HexCode = "#FF00FF", Status = "none" },
            new ColorModel { Name = "maroon", HexCode = "#800000", Status = "none" },
            new ColorModel { Name = "mediumaquamarine", HexCode = "#66CDAA", Status = "none" },
            new ColorModel { Name = "mediumblue", HexCode = "#0000CD", Status = "none" },
            new ColorModel { Name = "mediumorchid", HexCode = "#BA55D3", Status = "none" },
            new ColorModel { Name = "mediumpurple", HexCode = "#9370DB", Status = "none" },
            new ColorModel { Name = "mediumseagreen", HexCode = "#3CB371", Status = "none" },
            new ColorModel { Name = "mediumslateblue", HexCode = "#7B68EE", Status = "none" },
            new ColorModel { Name = "mediumspringgreen", HexCode = "#00FA9A", Status = "none" },
            new ColorModel { Name = "mediumturquoise", HexCode = "#48D1CC", Status = "none" },
            new ColorModel { Name = "mediumvioletred", HexCode = "#C71585", Status = "none" },
            new ColorModel { Name = "midnightblue", HexCode = "#191970", Status = "none" },
            new ColorModel { Name = "mintcream", HexCode = "#F5FFFA", Status = "none" },
            new ColorModel { Name = "mistyrose", HexCode = "#FFE4E1", Status = "none" },
            new ColorModel { Name = "moccasin", HexCode = "#FFE4B5", Status = "none" },
            new ColorModel { Name = "navajowhite", HexCode = "#FFDEAD", Status = "none" },
            new ColorModel { Name = "navy", HexCode = "#000080", Status = "none" },
            new ColorModel { Name = "oldlace", HexCode = "#FDF5E6", Status = "none" },
            new ColorModel { Name = "olive", HexCode = "#808000", Status = "none" },
            new ColorModel { Name = "olivedrab", HexCode = "#6B8E23", Status = "none" },
            new ColorModel { Name = "orange", HexCode = "#FFA500", Status = "none" },
            new ColorModel { Name = "orangered", HexCode = "#FF4500", Status = "none" },
            new ColorModel { Name = "orchid", HexCode = "#DA70D6", Status = "none" },
            new ColorModel { Name = "palegoldenrod", HexCode = "#EEE8AA", Status = "none" },
            new ColorModel { Name = "palegreen", HexCode = "#98FB98", Status = "none" },
            new ColorModel { Name = "paleturquoise", HexCode = "#AFEEEE", Status = "none" },
            new ColorModel { Name = "palevioletred", HexCode = "#DB7093", Status = "none" },
            new ColorModel { Name = "papayawhip", HexCode = "#FFEFD5", Status = "none" },
            new ColorModel { Name = "peachpuff", HexCode = "#FFDAB9", Status = "none" },
            new ColorModel { Name = "peru", HexCode = "#CD853F", Status = "none" },
            new ColorModel { Name = "pink", HexCode = "#FFC0CB", Status = "none" },
            new ColorModel { Name = "plum", HexCode = "#DDA0DD", Status = "none" },
            new ColorModel { Name = "powderblue", HexCode = "#B0E0E6", Status = "none" },
            new ColorModel { Name = "purple", HexCode = "#800080", Status = "none" },
            new ColorModel { Name = "red", HexCode = "#FF0000", Status = "none" },
            new ColorModel { Name = "rosybrown", HexCode = "#BC8F8F", Status = "none" },
            new ColorModel { Name = "royalblue", HexCode = "#4169E1", Status = "none" },
            new ColorModel { Name = "saddlebrown", HexCode = "#8B4513", Status = "none" },
            new ColorModel { Name = "salmon", HexCode = "#FA8072", Status = "none" },
            new ColorModel { Name = "sandybrown", HexCode = "#F4A460", Status = "none" },
            new ColorModel { Name = "seagreen", HexCode = "#2E8B57", Status = "none" },
            new ColorModel { Name = "seashell", HexCode = "#FFF5EE", Status = "none" },
            new ColorModel { Name = "sienna", HexCode = "#A0522D", Status = "none" },
            new ColorModel { Name = "silver", HexCode = "#C0C0C0", Status = "none" },
            new ColorModel { Name = "skyblue", HexCode = "#87CEEB", Status = "none" },
            new ColorModel { Name = "slateblue", HexCode = "#6A5ACD", Status = "none" },
            new ColorModel { Name = "slategray", HexCode = "#708090", Status = "none" },
            new ColorModel { Name = "snow", HexCode = "#FFFAFA", Status = "none" },
            new ColorModel { Name = "springgreen", HexCode = "#00FF7F", Status = "none" },
            new ColorModel { Name = "steelblue", HexCode = "#4682B4", Status = "none" },
            new ColorModel { Name = "tan", HexCode = "#D2B48C", Status = "none" },
            new ColorModel { Name = "teal", HexCode = "#008080", Status = "none" },
            new ColorModel { Name = "thistle", HexCode = "#D8BFD8", Status = "none" },
            new ColorModel { Name = "tomato", HexCode = "#FF6347", Status = "none" },
            new ColorModel { Name = "turquoise", HexCode = "#40E0D0", Status = "none" },
            new ColorModel { Name = "violet", HexCode = "#EE82EE", Status = "none" },
            new ColorModel { Name = "wheat", HexCode = "#F5DEB3", Status = "none" },
            new ColorModel { Name = "white", HexCode = "#FFFFFF", Status = "none" },
            new ColorModel { Name = "whitesmoke", HexCode = "#F5F5F5", Status = "none" },
            new ColorModel { Name = "yellow", HexCode = "#FFFF00", Status = "none" },
            new ColorModel { Name = "yellowgreen", HexCode = "#9ACD32", Status = "none" }
        };
        }
    }
}
